<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */

 // ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define( 'DB_NAME', 'wordpress' );
/** MySQL database username */
define( 'DB_USER', 'mattkrebs' );
/** MySQL database password */
define( 'DB_PASSWORD', 'matt1974' );
/** MySQL hostname */
define( 'DB_HOST', 'localhost' );
 
define('DISALLOW_FILE_MODS', false);
define('DISALLOW_FILE_EDIT', false);
 
 
require_once(dirname(__DIR__) . '/vendor/autoload.php');
require_once(dirname(__DIR__) . '/config/application.php');
require_once(ABSPATH . 'wp-settings.php');